version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        networks:
            - laravel_network

    mysql:
        image: mysql:8
        container_name: mysql_local
        environment:
            MYSQL_DATABASE: turk_ticaret_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    mysql_data:
